In [211]:
from NN import *

nn = NN(1, 3, 4, 3, 1).func(lambda x: np.maximum(0, x))

In [212]:
nn([[1]])

(array([[0.]]),
 [array([[0.28479014, 0.19810867, 0.31130256]]),
  array([[-0.7132709 ,  0.93072987, -0.31513722,  0.5441497 ]]),
  array([[ 0.3348337 ,  1.0245998 , -2.69565305]]),
  array([[-1.83560484]])],
 [array([[0.28479014, 0.19810867, 0.31130256]]),
  array([[0.        , 0.93072987, 0.        , 0.5441497 ]]),
  array([[0.3348337, 1.0245998, 0.       ]]),
  array([[0.]])])